### ISSUE TITLE
Timeline date highlighting incorrectly positioned

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#187] opened 2015-05-01 17:26 UTC
When viewing individual dates on the timeline associated with a document, the yellow highlight in the popup text consistently appears to the right of the actual date. Behavior observed in Chrome and Firefox.

![screen shot 2015-05-01 at 1 23 07 pm](https://cloud.githubusercontent.com/assets/273891/7434103/9a68d320-f005-11e4-916f-a2d4f28fb822.png)

**Comment by reefdog** [comment] 2015-05-08 22:37
Don't quote know *why* yet, but instead of wrapping the target characters, it's wrapping the same number of characters just after it. So where it should be: `Thing happened on <span class="occurrence">Dec 2., 1988</span> and was really important`, it's instead: `Thing happened on Dec 2., 1988<span class="occurrence"> and was rea</span>lly important`.

**Comment by reefdog** [comment] 2015-05-08 23:04
I'm mildly concerned that with 561e8cc5b28e78e601a240442384b39c8aa30229 we started storing the *end* of the matched string position instead of the beginning as the entity offset.

@nathanstitt, how confident are you that `@scanner.charpos` is returning the character position of the *beginning* of the match? Because the way I read [charpos](https://www.omniref.com/ruby/2.1.2/symbols/StringScanner#line=397), it returns the position of the scan pointer, which at that point would be the end of the match, right?

**Comment by nathanstitt** [comment] 2015-05-14 14:32
Yes, right you are. charpos returns the end of the match, not the beginning.

A short test I whipped up to verify:
```ruby
require 'strscan'
sentence = "ä short string with UTF …"
ss=StringScanner.new(sentence)
['ä', 'with'].each do | match |
    ss.scan_until(/#{match}/)
    print "%-3i: " % ss.charpos
    puts sentence[ss.charpos-match.length .. ss.charpos]
end
```
Outputs:
```text
   1  : ä
   19 : with
```
I't hard to remember but I think 561e8cc was done while we were trying to stabilize the platform after the initial move from Ruby 1.8, and was a case of "well it's much better than it was before at least".  Since prior to that it was all over the place on highlighting and was actually crashing on some UTF strings.  

Looks like I should have read the docs for strscan more carefully, great catch!

**Comment by reefdog** [comment] 2015-05-14 16:02
Thanks for your help confirming that @nathanstitt! I've committed the fix and a test.

We're going to have to reprocess all docs to generate the corrected positions. I was hoping we could just run a script on `entity_dates`, parsing out the occurrences and adjusting the offset (since it's consistently off by its own length), but we don't know exactly what docs were affected. We could probably at least narrow our reprocessing to docs uploaded between 2/6/2014 (when 561e8cc5b28e78e601a240442384b39c8aa30229 was committed) to now, unless we never actually reprocessed the docs from before then that that commit was intended to fix.

So, yeah.

**Comment by nathanstitt** [comment] 2015-05-14 16:04
Yeah not great. I think you'll actually want to re-process them all though. Before the commit the offset was actually worse, since we were using Ruby 1.8 and any doc that had UTF was wildly inaccurate.

**Comment by reefdog** [comment] 2015-05-14 16:08
Very good to know.

**Closed** 2015-05-14 16:07 UTC
Labels: bug, workspace
