### ISSUE TITLE
Default search facets for unauthenticated users include junk values

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#390] opened 2016-05-17 12:09 UTC
If you arrive at our `/public/search` page and are not logged in, your first click on the search bar may reveal several filtering values that are not part of the standard set. This is potentially confusing.

![screen shot 2016-05-17 at 8 01 06 am](https://cloud.githubusercontent.com/assets/273891/15321727/4ae9841a-1c06-11e6-8889-67af8f4c2ce1.png)

In this case, the extra values appeared from documents that showed in the first 10 most recent uploads.

**Comment by reefdog** [comment] 2016-05-17 14:05
This is actually a feature, not a bug. The bug, IMO, is that the default facets aren't visually distinguished from the dynamic ones. I recommend closing this in favor of #210.

**Closed** 2016-05-17 14:13 UTC
Labels: bug, topic: search
