### ISSUE TITLE
help tab not working from within pages in the help section

### ISSUE THREAD

**Issue by bobweston** [documentcloud/documentcloud#122] opened 2014-08-14 20:54 UTC
Once you click on a page under the Help section (let's say the "Publishing Documents, Notes, and Document Sets" link), if you click the Help tab at the top of the page, nothing happens.

Clicking on this link should take you back to the main help page.

**Comment by nathanstitt** [comment] 2015-02-09 20:33
Hi @bobweston,

Sorry for the belated reply on this.  I'm not sure that the proper behavior would be to switch the help document back to the "Introduction" document when the tab is clicked a second time.

It seems to me that expected behavior of a tab would be to switch the contents to the last thing that was displayed on the tab.  

For instance if I'm reading the "Publishing Documents, Notes ..." help document, and then switch off the tab and work on a document, the next time I click on the Help tab it should take me back to the same "Publishing" document that I left off reading.  This is what it currently does.

From the above reasoning, If I'm already reading a help document, and re-click the Help tab, no action should be taken, since I'm already in the Help section.

This is the expected behavior of all tab based user interfaces that I'm aware of.  The most popular of which is web-browsers, and it'd be silly for them to re-load the web-page whenever you switched back to a tab.

I'm going to close this issue for now, but please re-open it if you have additional reasoning to share or a use-case where it makes sense for you.

**Closed by nathanstitt** 2015-02-09 20:33 UTC

**Comment by jashkenas** [comment] 2015-02-13 21:58
@nathanstitt -- Quite right. The tab shouldn't bounce you to a different page if you click on it. Even if it's already open.
